FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY drip_compound.py .
COPY utils.py .

CMD [ "python", "drip_compound.py" ]

# docker build -f dockerfile.dripcompound -t dripcompound:latest .
# docker run --env-file drip_compound.env --name dripcompound -d dripcompound:latest
